# Generated by Django 3.2.4 on 2021-07-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_favorite_bag_in_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='in_bag',
            field=models.BooleanField(default=True),
        ),
    ]
