# Generated by Django 3.2.4 on 2021-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_bag_in_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
